### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by hhnguyen7** [BatsResearch/wiser#14]
Hi,
I got this error when I installed the requirements:
Command "/Users/hhn/Downloads/wiser-master/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/cb/kfn733tn4fd4d138_x8d3jyw0000gn/T/pip-install-0bgohfg6/jsonnet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/cb/kfn733tn4fd4d138_x8d3jyw0000gn/T/pip-record-_b0587be/install-record.txt --single-version-externally-managed --compile --install-headers /Users/hhn/Downloads/wiser-master/env/include/site/python3.6/jsonnet" failed with error code 1 in /private/var/folders/cb/kfn733tn4fd4d138_x8d3jyw0000gn/T/pip-install-0bgohfg6/jsonnet/

And this error when installing from source:
Could not find a version that satisfies the requirement labelmodels (from wiser==0.0.1) (from versions: )
No matching distribution found for labelmodels (from wiser==0.0.1)

Could you please help. 
Thank you. 
Hoang

**Comment by safranchik** [comment]
Hello Hoang,

I see you're using python 3.6. Can you please check if the error goes away when installing the requirements using python >= 3.8?

Installing from source may not work directly because you first need to install the [labelmodels](https://github.com/BatsResearch/labelmodels) repo.

Esteban

**Comment by hhnguyen7** [comment]
Hi Esteban,
Using python 3.7 resolved the issue.
Python 3.8 gave a spacy dependencies loading error.
Thanks!
Hoang
