### ISSUE TITLE
Elmo Linking Rule Latency

### ISSUE THREAD

**Issue by ajayluong** [BatsResearch/wiser#15]
Hi, 

We are using the native AllenNLP Elmo Linking in the Tagging/Linking Rules, and it seems to stall at this step. Have you seen any historical issues with this step? 

I think some clarity on how long the step takes to run? OR how we may speed up the process would be greatly appreciated. 

Thank you!

**Comment by ajayluong** [comment]
Hi, 

Follow-up on the question - I have found a way to spell out the time.
By utilizing the tqdm.a

**Comment by safranchik** [comment]
Thank you for your suggestion! 

Adding the tqdm_auto wrapper looks like the best way to display the progress to users.
