### ISSUE TITLE
Generative Model GPU Training

### ISSUE THREAD

**Issue by mkartik** [BatsResearch/wiser#21]
Hi,

Hope you guys are doing well! We were able to get a significant improvement in our NER model, by using WISER. We observed that training the LinkedHMM model is taking time for a large training set. Is there a way, we would be able to train the LinkedHMM model on GPU, as we observed that the code inherently uses torch tensors.

Please let me know, if you require any further clarifications that might help you answer our question.

Thanks,
Kartik

**Comment by safranchik** [comment]
Hello Kartik,

Thank you so much for your message! We're really glad to hear that you were successfully able to use Wiser to improve your NER model!

As of now, there is no configuration to train the generative models on GPU. However, we expect to make such an update in the near future.

In the meantime, to speed up the generative training process, here's what you can do:

1. Manually edit your local version of [labelmodels](https://github.com/BatsResearch/labelmodels) to run on GPU.

2. Train the LinkedHMM on a subset of the unlabeled training data, but the discriminative model on the entire dataset. In the past, we have been able to obtain very good results by training the generative models using a fraction of the unlabeled data, with little to no changes in discriminative end-performance. To do so, you will need to train your gen. model using a fraction of the dataset (e.g., `model.train(config, train_data=train_data[:1000], dev_data=dev_data)`, and then generate and save the LinkedHMM's probabilistic output for the entire dataset (e.g., `model.save_output(data=train_data, ...`).

I hope this makes sense, and please let me know if you have any questions!

Esteban
