### ISSUE TITLE
No module  wiser.rules

### ISSUE THREAD

**Issue by thak123** [BatsResearch/wiser#24]
```
from wiser.rules import TaggingRule

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-15-21381514e417> in <module>
----> 1 from wiser.rules import TaggingRule

ModuleNotFoundError: No module named 'wiser.rules'

```

**Comment by thak123** [comment]
My fault... Had installed via direct pip. Installed using  **pip install .**. works fine now.

**Comment by sumanthd17** [comment]
I tried with using pip install -r requirements.txt but still I'm having this issue. Can you elaborate on the fix that you used?
Thanks

**Comment by safranchik** [comment]
Can you please try running pip3 install -r requirements.txt?

> I tried with using pip install -r requirements.txt but still I'm having this issue. Can you elaborate on the fix that you used?
> Thanks
