### ISSUE TITLE
config.epochs not config.num_epochs

### ISSUE THREAD

**Issue by david-waterworth** [BatsResearch/wiser#31]
The generative model tutorial sets `config.num_epochs=5` but in face the parameter is `config.epochs` (the default is 5 so it appears correct)

https://github.com/BatsResearch/labelmodels/blob/3b5683bef7ee902dc205a8cd93572b05b88dbad5/labelmodels/label_model.py#L72-L92

**Comment by ChaceHayhurst** [comment]
Nice catch. Fixed it in pr 32 (https://github.com/BatsResearch/wiser/pull/32). Thanks!
